[MolecularFormulaSearch]
url_database = "postgresql+psycopg2://coremsappdb:coremsapppnnl@localhost:5432/coremsapp"
error_method = 'None'
score_method = 'prob_score'
min_ppm_error  = -1
max_ppm_error = 1
min_dbe = 0
max_dbe = 50
use_isotopologue_filter = false
min_abun_error = -30
max_abun_error = 70
use_min_peaks_filter = true
min_peaks_per_class = 10 
adduct_atoms_neg = ['Cl']
adduct_atoms_pos = ['Na']
isProtonated = true
isRadical= false
isAdduct = false

[MolecularFormulaSearch.usedAtoms]
C = [ 1, 90,]
H = [ 4, 200,]
O = [ 1, 23,]
N = [ 0, 2,]
S = [ 0, 1,]
Cl = [ 0, 0,]
Br = [ 0, 0,]
P = [ 0, 0,]
Na = [ 0, 0,]
