[MolecularFormulaSearch]
use_isotopologue_filter = false
isotopologue_filter_threshold = 33.0
isotopologue_filter_atoms = [ "Cl", "Br",]
use_runtime_kendrick_filter = false
use_min_peaks_filter = true
min_peaks_per_class = 15
url_database = "sqlite:///db/molformula.db"
db_jobs = 3
db_chunk_size = 300
ion_charge = -1
min_hc_filter = 0.3
max_hc_filter = 3.0
min_oc_filter = 0.0
max_oc_filter = 1.2
min_op_filter = 2.0
use_pah_line_rule = false
min_dbe = 0.0
max_dbe = 40.0
mz_error_score_weight = 0.6
isotopologue_score_weight = 0.4
adduct_atoms_neg = [ "Cl", "Br",]
adduct_atoms_pos = [ "Na", "K",]
score_methods = [ "S_P_lowest_error", "N_S_P_lowest_error", "lowest_error", "prob_score", "air_filter_error", "water_filter_error", "earth_filter_error",]
score_method = "prob_score"
output_min_score = 0.1
output_score_method = "All Candidates"
isRadical = false
isProtonated = true
isAdduct = false
ionization_type = "ESI"
min_ppm_error = -10.0
max_ppm_error = 10.0
min_abun_error = -100.0
max_abun_error = 100.0
mz_error_range = 1.5
error_method = "None"
mz_error_average = 0.0

[Transient]
implemented_apodization_function = [ "Hamming", "Hanning", "Blackman", "Full-Sine", "Half-Sine", "Kaiser", "Half-Kaiser",]
apodization_method = "Hanning"
number_of_truncations = 0
number_of_zero_fills = 1
next_power_of_two = false
kaiser_beta = 8.6

[MassSpectrum]
noise_threshold_method = "log"
noise_threshold_methods_implemented = [ "minima", "signal_noise", "relative_abundance", "absolute_abundance", "log",]
noise_threshold_min_std = 6
noise_threshold_min_s2n = 4.0
noise_threshold_min_relative_abundance = 6.0
noise_threshold_absolute_abundance = 1000000.0
noise_threshold_log_nsigma = 6
noise_threshold_log_nsigma_corr_factor = 0.463
noise_threshold_log_nsigma_bins = 500
noise_min_mz = 50.0
noise_max_mz = 1200.0
min_picking_mz = 50.0
max_picking_mz = 1200.0
picking_point_extrapolate = 3
calib_minimize_method = "Powell"
calib_pol_order = 2
max_calib_ppm_error = 1.0
min_calib_ppm_error = -1.0
calib_sn_threshold = 2.0
calibration_ref_match_method = "legacy"
calibration_ref_match_method_implemented = [ "legacy", "merged",]
calibration_ref_match_tolerance = 0.003
calibration_ref_match_std_raw_error_limit = 1.5
do_calibration = true

[MassSpecPeak]
kendrick_rounding_method = "floor"
implemented_kendrick_rounding_methods = [ "floor", "ceil", "round",]
peak_derivative_threshold = 0.0
peak_min_prominence_percent = 0.1
min_peak_datapoints = 5.0
peak_max_prominence_percent = 0.1
peak_height_max_percent = 10.0
legacy_resolving_power = true
centroid_legacy_polyfit = false

[MolecularFormulaSearch.usedAtoms]
C = [ 1, 100,]
H = [ 1, 200,]

[MolecularFormulaSearch.used_atom_valences]
C = 4
13C = 4
N = 3
O = 2
S = 2
H = 1
F = 1
Cl = 1
Br = 1
I = 1
At = 1
Li = 1
Na = 1
K = 1
Rb = 1
Cs = 1
Fr = 1
B = 4
In = 3
Al = 3
P = 3
Ga = 3
Mg = 2
Be = 2
Ca = 2
Sr = 2
Ba = 2
Ra = 2
V = 5
Fe = 3
Si = 4
Sc = 3
Ti = 4
Cr = 1
Mn = 1
Co = 1
Ni = 1
Cu = 2
Zn = 2
Ge = 4
As = 5
Se = 6
Y = 3
Zr = 4
Nb = 5
Mo = 6
Tc = 7
Ru = 8
Rh = 6
Pd = 4
Ag = 0
Cd = 2
Sn = 4
Sb = 5
Te = 6
La = 3
Hf = 4
Ta = 5
W = 6
Re = 4
Os = 4
Ir = 4
Pt = 4
Au = 3
Hg = 1
Tl = 3
Pb = 4
Bi = 3
Po = 2
Ac = 3

[MassSpecPeak.kendrick_base]
C = 1
H = 2

[DataInput.header_translate]
"m/z" = "m/z"
mOz = "m/z"
Mass = "m/z"
"Resolving Power" = "Resolving Power"
"Res." = "Resolving Power"
resolution = "Resolving Power"
Intensity = "Peak Height"
"Peak Height" = "Peak Height"
I = "Peak Height"
Abundance = "Peak Height"
abs_abu = "Peak Height"
"Signal/Noise" = "S/N"
"S/N" = "S/N"
sn = "S/N"