raw_file_start_scan = 1
raw_file_final_scan = 7
file_paths = "data/raw_data/*"
output_directory = "data/output"
output_group_name = "..."
output_type = "csv"
polarity = -1
is_centroid = true
corems_toml_path = "configuration/di_corems.toml"
calibrate = true
batch_calibrate = true
calibration_ref_file_path = "data/reference/Hawkes_neg.ref"
plot_mz_error = true
plot_ms_assigned_unassigned = true
plot_c_dbe = true
plot_van_krevelen = true
plot_ms_classes = true
plot_mz_error_classes = true
plot_qc = true