raw_file_start_scan = 1
raw_file_final_scan = 7
file_paths = [ "data/raw_data/20190709_WK_CADY_Auto_S16_H1_Post_O5_1_01_36.tsv" ]
output_directory = "output"
output_group_name = "..."
output_type = "csv"
polarity = -1
is_centroid = true
corems_toml_path = "configuration/corems.toml"
nmdc_metadata_path = "configuration/nmdc_metadata.json"
calibrate = true
calibration_ref_file_path = "data/raw_data/SRFA.ref"
plot_mz_error = true
plot_ms_assigned_unassigned = true
plot_c_dbe = true
plot_van_krevelen = true
plot_ms_classes = true
plot_mz_error_classes = true