[MassSpectrum]
noise_threshold_method = 'log'
noise_threshold_log_nsigma = 10
picking_point_extrapolate = 3
min_picking_mz = 100
max_picking_mz = 700
noise_min_mz = 100
noise_max_mz = 700
calib_pol_order = 2
calib_sn_threshold = 10
calibration_ref_match_method = 'merged'
calibration_ref_match_tolerance = 0.003
verbose_processing = false

[MolecularFormulaSearch]
url_database = ""
error_method = 'None'
score_method = 'prob_score'
min_ppm_error  = -1
max_ppm_error = 1
min_dbe = 0
max_dbe = 50
use_isotopologue_filter = false
min_abun_error = -30
max_abun_error = 70
use_min_peaks_filter = true
min_peaks_per_class = 10
adduct_atoms_neg = ['Cl']
adduct_atoms_pos = ['Na']
isProtonated = true
isRadical= false
isAdduct = false
verbose_processing = false

[MolecularFormulaSearch.usedAtoms]
C = [ 1, 90,]
H = [ 4, 200,]
O = [ 1, 23,]
N = [ 0, 2,]
S = [ 0, 1,]
Cl = [ 0, 0,]
Br = [ 0, 0,]
P = [ 0, 0,]
Na = [ 0, 0,]

[MassSpecPeak]
legacy_resolving_power = false
legacy_centroid_polyfit = false
peak_min_prominence_percent = 0.01